version: "3.7"
services:
  palomita:
    image: node:16
    working_dir: /app
    volumes:
      - ../:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CODESANDBOX_SSE=true
    command: bash -c "npm install && npm run serve"
    ports:
      - "8080:8080"
